import React from "react";
import type {Metadata} from "next";
import {ClerkProvider} from "@clerk/nextjs";
import {Nunito} from "next/font/google";
import {Toaster} from "@/components/ui/sonner"
import "./globals.css";

const fontNunito = Nunito({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
}

export default function RootLayout({children}: Props) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={fontNunito.className}>{children}</body>
      <Toaster/>
      </html>
    </ClerkProvider>
  );
}
